CREATE OR REPLACE PROCEDURE sh_obj_filter(p_tname IN VARCHAR2) IS v_retc CLOB;
BEGIN
v_retc := DBMS_STATS.CONFIGURE_ADVISOR_OBJ_FILTER(p_tname, 'EXECUTE',NULL,NULL,NULL,'DISABLE');
v_retc := DBMS_STATS.CONFIGURE_ADVISOR_OBJ_FILTER(p_tname, 'EXECUTE',NULL,'OE',NULL,'ENABLE');
END;
/
