CREATE DATABASE cdbdev  
USER SYS IDENTIFIED BY fenago 
USER SYSTEM IDENTIFIED BY fenago
EXTENT MANAGEMENT LOCAL 
DEFAULT TEMPORARY TABLESPACE temp
DEFAULT TABLESPACE users
UNDO TABLESPACE undotbs1
ENABLE PLUGGABLE DATABASE;
