CREATE SMALLFILE TABLESPACE INVENTORY 
    DATAFILE 
        '/u01/app/oracle/oradata/ORCLCDB/orclpdb1/INVENTORY01.DBF' SIZE 5242880 
    DEFAULT NOCOMPRESS 
    ONLINE 
    SEGMENT SPACE MANAGEMENT AUTO 
    EXTENT MANAGEMENT LOCAL AUTOALLOCATE;
