CREATE SMALLFILE TABLESPACE INVENTORY 
    DATAFILE 
        '/u02/app/oracle/oradata/ORCL/PDB1/INVENTORY01.DBF' SIZE 5242880 
    DEFAULT NOCOMPRESS 
    ONLINE 
    SEGMENT SPACE MANAGEMENT AUTO 
    EXTENT MANAGEMENT LOCAL AUTOALLOCATE;
